/*
 * This source file was generated by the Gradle 'init' task
 */
package org.search;

public class Search {
    public String getGreeting() {
        return "Hello Search!";
    }

    public static void main(String[] args) {
        System.out.println(new Search().getGreeting());
    }
}
